package entity;

import java.util.Date;

public class Car {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car.carID
     *
     * @mbg.generated
     */
    private String carid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car.carType
     *
     * @mbg.generated
     */
    private String cartype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car.carOrigin
     *
     * @mbg.generated
     */
    private String carorigin;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car.route
     *
     * @mbg.generated
     */
    private String route;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car.carProDate
     *
     * @mbg.generated
     */
    private Date carprodate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car.carBuyDate
     *
     * @mbg.generated
     */
    private Date carbuydate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car.COMMENT
     *
     * @mbg.generated
     */
    private String comment;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car.carID
     *
     * @return the value of car.carID
     *
     * @mbg.generated
     */
    public String getCarid() {
        return carid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car.carID
     *
     * @param carid the value for car.carID
     *
     * @mbg.generated
     */
    public void setCarid(String carid) {
        this.carid = carid == null ? null : carid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car.carType
     *
     * @return the value of car.carType
     *
     * @mbg.generated
     */
    public String getCartype() {
        return cartype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car.carType
     *
     * @param cartype the value for car.carType
     *
     * @mbg.generated
     */
    public void setCartype(String cartype) {
        this.cartype = cartype == null ? null : cartype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car.carOrigin
     *
     * @return the value of car.carOrigin
     *
     * @mbg.generated
     */
    public String getCarorigin() {
        return carorigin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car.carOrigin
     *
     * @param carorigin the value for car.carOrigin
     *
     * @mbg.generated
     */
    public void setCarorigin(String carorigin) {
        this.carorigin = carorigin == null ? null : carorigin.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car.route
     *
     * @return the value of car.route
     *
     * @mbg.generated
     */
    public String getRoute() {
        return route;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car.route
     *
     * @param route the value for car.route
     *
     * @mbg.generated
     */
    public void setRoute(String route) {
        this.route = route == null ? null : route.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car.carProDate
     *
     * @return the value of car.carProDate
     *
     * @mbg.generated
     */
    public Date getCarprodate() {
        return carprodate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car.carProDate
     *
     * @param carprodate the value for car.carProDate
     *
     * @mbg.generated
     */
    public void setCarprodate(Date carprodate) {
        this.carprodate = carprodate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car.carBuyDate
     *
     * @return the value of car.carBuyDate
     *
     * @mbg.generated
     */
    public Date getCarbuydate() {
        return carbuydate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car.carBuyDate
     *
     * @param carbuydate the value for car.carBuyDate
     *
     * @mbg.generated
     */
    public void setCarbuydate(Date carbuydate) {
        this.carbuydate = carbuydate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car.COMMENT
     *
     * @return the value of car.COMMENT
     *
     * @mbg.generated
     */
    public String getComment() {
        return comment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car.COMMENT
     *
     * @param comment the value for car.COMMENT
     *
     * @mbg.generated
     */
    public void setComment(String comment) {
        this.comment = comment == null ? null : comment.trim();
    }
}